"""Offline regression for api/charter_pages.py — charter citations a reader can act on.

Run:  python test_charter_pages.py   (or: pytest test_charter_pages.py)

The bug this guards: a reply cited "CvSU Citizens' Charter, FY 2026 edition,
p. 997" — a number that says nothing about what is on the page, and that is not
even the number printed on it (997 is the PDF index; the page says 948).

Two layers are covered. The SERVING layer (this module) must read
data/charter_structure.json and render it faithfully, degrading a field at a
time rather than inventing one. The DATA layer — the structure file itself,
generated by scripts/build_charter_structure.py and hand-editable — must stay
internally consistent and keep saying the right thing about the pages the app
actually cites, so a regenerated edition cannot quietly ship a wrong citation.
"""
import json

from api import charter_pages as cp

# Fixed points in the FY 2026 charter, verified against the OCR text.
ENROLLMENT_PDF_PAGE = 997
ENROLLMENT_PRINTED = 948
FRONT_MATTER_PAGE = 2       # unnumbered, before any section
APPENDIX_PAGE = 2024        # "Contact Information" — inside no service section

STRUCTURE = json.loads(open(cp.STRUCTURE_PATH, encoding="utf-8").read())


def _check(cond, msg, fails):
    print(f"{'PASS' if cond else 'FAIL'}  {msg}")
    if not cond:
        fails.append(msg)


# ── serving layer ────────────────────────────────────────────────────────────

def test_index_loads_the_structure_file():
    idx = cp.get_index()
    assert idx is not None and idx.available
    snap = idx.snapshot()
    assert snap["sections"] > 800
    assert snap["edition"] == "FY 2026"
    assert snap["page_offset"] == 49


def test_describes_a_service_page():
    info = cp.describe(ENROLLMENT_PDF_PAGE)
    assert info.printed_page == ENROLLMENT_PRINTED
    assert info.title == "Registration of Continuing Students (via Portal)"
    assert info.office == "Office of the Campus Registrar"
    assert info.page_label == f"p. {ENROLLMENT_PRINTED}"


def test_citation_shows_the_printed_page_not_the_pdf_index():
    cite = cp.cite_page(ENROLLMENT_PDF_PAGE)
    assert cite.startswith("CvSU Citizens' Charter, FY 2026 edition, p. 948")
    assert "Registration of Continuing Students" in cite
    assert "Office of the Campus Registrar" in cite
    assert str(ENROLLMENT_PDF_PAGE) not in cite


def test_a_continuation_page_inherits_its_own_procedure():
    """p.604 continues the counselling procedure from p.603. Its first line is
    a numbered CLIENT STEP ("5. Fill out counselling/"), which a naive heading
    rule read as the service title."""
    info = cp.describe(604)
    assert info.title == "Counseling Procedure for Students"


def test_pages_in_no_section_claim_no_service():
    """Front matter and the contact-table appendix document no service. They
    must say nothing rather than inherit the procedure printed above them."""
    for page in (FRONT_MATTER_PAGE, APPENDIX_PAGE, 2025, 2026):
        assert cp.describe(page).title is None
    assert cp.cite_page(FRONT_MATTER_PAGE) == "CvSU Citizens' Charter, FY 2026 edition, p. 2"
    assert cp.cite_page(APPENDIX_PAGE) == "CvSU Citizens' Charter, FY 2026 edition, p. 1975"


def test_a_page_past_the_end_gets_no_invented_number():
    """A stale binding must not be dressed up as a plausible printed page."""
    info = cp.describe(999999)
    assert info.pdf_page == 999999 and info.printed_page is None and info.title is None
    assert "p. 999999" in cp.cite_page(999999)


def test_deep_link_uses_the_pdf_index_not_the_printed_page(monkeypatch):
    monkeypatch.setattr(cp, "PDF_URL", "https://api.example/sources/citizens-charter.pdf")
    # The fragment must be the PDF page (997) — a viewer counts pages, it does
    # not read the number printed on them.
    assert cp.page_url(ENROLLMENT_PDF_PAGE) == \
        f"https://api.example/sources/citizens-charter.pdf#page={ENROLLMENT_PDF_PAGE}"


def test_links_to_this_api_with_no_configuration(monkeypatch):
    """The out-of-the-box path: no CHARTER_PDF_URL, but the request's own
    origin is bound, so the citation still links to a page the reader can open."""
    monkeypatch.setattr(cp, "PDF_URL", "")
    monkeypatch.setattr(cp, "_request_origin", cp.ContextVar("t", default=""))
    assert cp.page_url(ENROLLMENT_PDF_PAGE) is None      # nothing bound yet

    cp.set_request_origin("https://sevi-api.example/")   # trailing slash tolerated
    assert cp.page_url(ENROLLMENT_PDF_PAGE) == \
        f"https://sevi-api.example{cp.ROUTE_PATH}#page={ENROLLMENT_PDF_PAGE}"


def test_no_self_link_when_the_pdf_is_not_in_the_build(monkeypatch):
    """A link we generate ourselves must not 404 — if the image dropped the
    PDF, cite without linking. An explicit CHARTER_PDF_URL is the operator's
    call and is never second-guessed."""
    monkeypatch.setattr(cp, "PDF_URL", "")
    monkeypatch.setattr(cp, "_request_origin", cp.ContextVar("t", default=""))
    monkeypatch.setattr(cp, "PDF_PATH", "/no/such/charter.pdf")
    cp.set_request_origin("https://sevi-api.example")
    assert cp.page_url(ENROLLMENT_PDF_PAGE) is None

    monkeypatch.setattr(cp, "PDF_URL", "https://cvsu.example/charter.pdf")
    assert cp.page_url(ENROLLMENT_PDF_PAGE) == \
        f"https://cvsu.example/charter.pdf#page={ENROLLMENT_PDF_PAGE}"


def test_a_missing_structure_file_degrades_to_a_bare_page_reference(tmp_path, monkeypatch):
    """The corpus can be absent (a slimmed image). Citations must lose detail,
    not raise — and must not claim a printed page they cannot know."""
    idx = cp.PageIndex(str(tmp_path / "nope.json"))
    assert not idx.available
    monkeypatch.setattr(cp, "_index", idx)
    assert cp.describe(ENROLLMENT_PDF_PAGE).title is None
    assert cp.cite_page(ENROLLMENT_PDF_PAGE) == \
        f"CvSU Citizens' Charter, FY 2026 edition, p. {ENROLLMENT_PDF_PAGE}"


def test_both_tiers_cite_a_page_identically():
    """charter_rag (RAG tier) and intent_grounding (curated tier) must not
    drift apart — the whole reason page rendering lives in one module."""
    from api import charter_rag, intent_grounding

    passage = charter_rag.Passage(score=0.5, page=ENROLLMENT_PDF_PAGE, text="x")
    ref = intent_grounding.SourceRef(kind="charter", locator=str(ENROLLMENT_PDF_PAGE))
    assert passage.citation() == ref.citation() == cp.cite_page(ENROLLMENT_PDF_PAGE)


def test_a_corrupt_binding_does_not_break_a_reply():
    """Bindings are hand-reviewed, so a non-numeric locator is a broken file —
    it must degrade to an unknown page, not 500 the chat turn."""
    from api import intent_grounding

    ref = intent_grounding.SourceRef(kind="charter", locator="not-a-page")
    assert "CvSU Citizens' Charter" in ref.citation()


# ── the origin a citation links to ───────────────────────────────────────────

def _origin(scheme="http", host="api.internal:8000", headers=None):
    """api.app._public_origin against a synthetic request."""
    from starlette.requests import Request
    from api.app import _public_origin

    raw = [(k.lower().encode(), v.encode()) for k, v in (headers or {}).items()]
    return _public_origin(Request({
        "type": "http", "http_version": "1.1", "method": "GET", "scheme": scheme,
        "path": "/chat", "root_path": "", "query_string": b"",
        "headers": raw + [(b"host", host.encode())], "server": ("api.internal", 8000),
    }))


def test_origin_follows_the_proxy_scheme():
    """Behind a TLS-terminating proxy the ASGI scope still says http, so an
    unpatched base_url yields an http link on an https page — which the browser
    blocks as mixed content. This is the check that caught it."""
    assert _origin() == "http://api.internal:8000/"
    assert _origin(headers={"X-Forwarded-Proto": "https"}) == "https://api.internal:8000/"
    assert _origin(headers={
        "X-Forwarded-Proto": "https", "X-Forwarded-Host": "sevi.cvsu.edu.ph",
    }) == "https://sevi.cvsu.edu.ph/"
    # Proxies append, so the client-facing value is the first one.
    assert _origin(headers={"X-Forwarded-Proto": "https, http"}).startswith("https://")


def test_origin_ignores_junk_proxy_headers():
    """The headers are client-controlled. A value that is not a plain scheme or
    host is dropped in favour of the real connection, so nothing exotic can be
    spliced into a link we render into a reply."""
    for bad in ("javascript:alert(1)//", "HTTPS://x", "", "ht tps"):
        assert _origin(headers={"X-Forwarded-Proto": bad}).startswith("http://api.internal")
    for bad in ("evil host", "a/b", "x\nSet-Cookie: y", ""):
        assert _origin(headers={"X-Forwarded-Host": bad}) == "http://api.internal:8000/"


# ── data layer: data/charter_structure.json ──────────────────────────────────

def test_structure_file_is_internally_consistent():
    sections = STRUCTURE["sections"]
    assert STRUCTURE["printed_from"] == STRUCTURE["page_offset"] + 1
    prev_end = 0
    for s in sections:
        first, last = s["pages"]
        assert first <= last, f"{s['title']!r} has a backwards range"
        assert first > prev_end, f"{s['title']!r} overlaps the section before it"
        assert 1 <= first <= STRUCTURE["pdf_pages"], f"{s['title']!r} is off the document"
        assert s["title"], "every section must be titled"
        prev_end = last


def test_every_cited_charter_page_resolves_to_a_section():
    """The pages the app actually cites — the applied intent bindings — must
    each land inside a titled section. A regenerated edition that shifted them
    into a gap would ship citations naming no service at all.

    Front matter is exempt: it documents no service by definition, and
    about_cvsu is deliberately bound to the agency profile on p. 2."""
    bindings = json.loads(
        open("data/intent_sources.json", encoding="utf-8").read()
    )["bindings"]
    unresolved = []
    for tag, refs in bindings.items():
        for ref in refs:
            page = int(ref["locator"]) if ref["kind"] == "charter" else None
            if page is None or page < STRUCTURE["printed_from"]:
                continue
            info = cp.describe(page)
            if not (info.title and info.printed_page):
                unresolved.append(f"{tag}:p.{page}")
    assert not unresolved, f"bound charter pages with no section: {unresolved}"


if __name__ == "__main__":
    fails: list[str] = []
    idx = cp.get_index()
    _check(idx is not None and idx.available, "index loads data/charter_structure.json", fails)

    snap = idx.snapshot()
    _check(snap["sections"] > 800, f"{snap['sections']} sections, offset {snap['page_offset']}", fails)

    info = cp.describe(ENROLLMENT_PDF_PAGE)
    _check(info.printed_page == ENROLLMENT_PRINTED,
           f"pdf p.{ENROLLMENT_PDF_PAGE} -> printed p.{info.printed_page}", fails)
    _check(info.title == "Registration of Continuing Students (via Portal)",
           f"service title — {info.title!r}", fails)
    _check(info.office == "Office of the Campus Registrar", f"office — {info.office!r}", fails)

    cite = cp.cite_page(ENROLLMENT_PDF_PAGE)
    _check(str(ENROLLMENT_PDF_PAGE) not in cite and "p. 948" in cite,
           f"citation shows the printed page — {cite!r}", fails)

    _check(cp.describe(604).title == "Counseling Procedure for Students",
           "a continuation page inherits its own procedure, not a client step", fails)
    _check(all(cp.describe(p).title is None for p in (FRONT_MATTER_PAGE, APPENDIX_PAGE, 2026)),
           "front matter and the appendix claim no service", fails)
    _check(cp.describe(999999).printed_page is None, "a page past the end invents no number", fails)

    _saved, _saved_origin = cp.PDF_URL, cp._request_origin
    try:
        cp.PDF_URL = ""
        cp._request_origin = cp.ContextVar("t", default="")
        _check(cp.page_url(ENROLLMENT_PDF_PAGE) is None,
               "no override and no bound origin -> no link", fails)
        cp.set_request_origin("https://sevi-api.example/")
        _check(cp.page_url(ENROLLMENT_PDF_PAGE)
               == f"https://sevi-api.example{cp.ROUTE_PATH}#page={ENROLLMENT_PDF_PAGE}",
               "links to the serving API with no configuration", fails)
        cp.PDF_URL = "https://api.example/sources/citizens-charter.pdf"
        _check(cp.page_url(ENROLLMENT_PDF_PAGE).startswith("https://api.example/"),
               "CHARTER_PDF_URL overrides the request origin", fails)
    finally:
        cp.PDF_URL, cp._request_origin = _saved, _saved_origin

    from api import charter_rag, intent_grounding
    same = (charter_rag.Passage(score=0.5, page=ENROLLMENT_PDF_PAGE, text="x").citation()
            == intent_grounding.SourceRef(kind="charter", locator=str(ENROLLMENT_PDF_PAGE)).citation())
    _check(same, "RAG tier and curated tier cite a page identically", fails)
    _check("CvSU Citizens' Charter" in
           intent_grounding.SourceRef(kind="charter", locator="not-a-page").citation(),
           "a corrupt locator degrades instead of raising", fails)

    # Data layer
    bad = []
    prev_end = 0
    for s in STRUCTURE["sections"]:
        first, last = s["pages"]
        if first > last or first <= prev_end or not s["title"]:
            bad.append(s["title"])
        prev_end = last
    _check(not bad, f"{len(STRUCTURE['sections'])} sections are ordered, titled and non-overlapping"
           + (f" — BAD: {bad[:5]}" if bad else ""), fails)

    bindings = json.loads(open("data/intent_sources.json", encoding="utf-8").read())["bindings"]
    unresolved = [
        f"{tag}:p.{r['locator']}"
        for tag, refs in bindings.items() for r in refs
        if r["kind"] == "charter" and int(r["locator"]) >= STRUCTURE["printed_from"]
        and not cp.describe(int(r["locator"])).title
    ]
    _check(not unresolved, "every bound charter page (past the front matter) lands in a section"
           + (f" — MISSING: {unresolved}" if unresolved else ""), fails)

    print(f"\n{'ALL PASS' if not fails else str(len(fails)) + ' FAILED'}")
    raise SystemExit(1 if fails else 0)
