"""
One-way data migration: logs/chat_history.db (SQLite) -> PostgreSQL.

Copies model_lookup, model_version, chat_messages, sessions, intent_stats,
and feedback with their ORIGINAL ids (the Postgres schema uses GENERATED BY
DEFAULT identity columns for exactly this reason), then bumps each identity
sequence past MAX(id) and verifies row counts + id checksums.

Usage (from the repo root):
    python scripts/migrate_chat_history_to_postgres.py \
        --dsn postgresql://user:pass@host:5432/dbname \
        [--sqlite logs/chat_history.db] [--batch 5000] [--force]

Or set DATABASE_URL instead of --dsn. The SQLite file is opened read-only.
Refuses to run against a Postgres DB that already has chat data unless
--force is given (--force truncates all six tables first).
"""

import argparse
import os
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import psycopg  # noqa: E402

from api.logger import _PG_SCHEMA, _INDEX_DDL  # noqa: E402
from api import model_registry  # noqa: E402

# Copy order matters only for readability (no FKs are enforced — see the
# schema comment in api/logger.py), but keep referenced tables first.
TABLES = [
    "model_lookup",
    "model_version",
    "chat_messages",
    "sessions",
    "intent_stats",
    "feedback",
]


def sqlite_columns(conn: sqlite3.Connection, table: str) -> list:
    return [r[1] for r in conn.execute(f"PRAGMA table_info({table})")]


def pg_columns(cur, table: str) -> list:
    cur.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = 'public' AND table_name = %s",
        (table,),
    )
    return [r[0] for r in cur.fetchall()]


def copy_table(sq: sqlite3.Connection, pg_cur, table: str, batch: int) -> int:
    src_cols = sqlite_columns(sq, table)
    if not src_cols:
        print(f"  {table}: not present in SQLite source - skipped")
        return 0
    dst_cols = pg_columns(pg_cur, table)
    dropped = [c for c in src_cols if c not in dst_cols]
    if dropped:
        print(f"  {table}: WARNING - SQLite columns not in Postgres schema, "
              f"data in them will NOT be copied: {', '.join(dropped)}")
    cols = [c for c in src_cols if c in dst_cols]
    col_list = ", ".join(cols)
    placeholders = ", ".join(["%s"] * len(cols))
    insert_sql = f"INSERT INTO {table} ({col_list}) VALUES ({placeholders})"

    src = sq.execute(f"SELECT {col_list} FROM {table}")
    copied = 0
    while True:
        rows = src.fetchmany(batch)
        if not rows:
            break
        pg_cur.executemany(insert_sql, rows)
        copied += len(rows)
        print(f"  {table}: {copied} rows...", end="\r")
    print(f"  {table}: {copied} rows copied ({len(cols)} columns)")
    return copied


def fix_sequence(pg_cur, table: str) -> None:
    pg_cur.execute(
        f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
        f"(SELECT COALESCE(MAX(id), 0) + 1 FROM {table}), false)"
    )


def verify(sq: sqlite3.Connection, pg_cur, table: str) -> bool:
    src_n = sq.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
    pg_cur.execute(f"SELECT COUNT(*) FROM {table}")
    dst_n = pg_cur.fetchone()[0]
    src_sum = sq.execute(f"SELECT COALESCE(SUM(id), 0) FROM {table}").fetchone()[0]
    pg_cur.execute(f"SELECT COALESCE(SUM(id), 0) FROM {table}")
    dst_sum = pg_cur.fetchone()[0]
    ok = src_n == dst_n and int(src_sum) == int(dst_sum)
    marker = "OK " if ok else "FAIL"
    print(f"  [{marker}] {table}: sqlite {src_n} rows (id-sum {src_sum}) | postgres {dst_n} rows (id-sum {dst_sum})")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sqlite", default="logs/chat_history.db")
    parser.add_argument("--dsn", default=os.getenv("DATABASE_URL"))
    parser.add_argument("--batch", type=int, default=5000)
    parser.add_argument("--force", action="store_true",
                        help="Truncate existing Postgres tables before copying")
    args = parser.parse_args()

    if not args.dsn:
        print("ERROR: pass --dsn or set DATABASE_URL")
        return 2
    sqlite_path = Path(args.sqlite)
    if not sqlite_path.exists():
        print(f"ERROR: SQLite source not found: {sqlite_path}")
        return 2

    print("NOTE: stop the API (or pause traffic) for the duration of the copy —")
    print("      rows written to SQLite mid-copy fail verification (safe: the")
    print("      Postgres transaction rolls back) or are missed if written after.")

    # Read-only so a live writer on the file can't be disturbed (and vice versa).
    sq = sqlite3.connect(f"file:{sqlite_path.as_posix()}?mode=ro", uri=True)

    # Only operate on tables that actually exist in the SQLite source. Older
    # deployments predate the model registry, so model_lookup/model_version
    # may be absent — in that case leave the API-seeded Postgres registry
    # alone (the migrated chat_messages carry NULL model_version_id anyway).
    present = [t for t in TABLES if sqlite_columns(sq, t)]
    absent = [t for t in TABLES if t not in present]
    if absent:
        print(f"Source SQLite has no: {', '.join(absent)} - those are skipped "
              f"(Postgres keeps whatever the API already seeded).")

    with psycopg.connect(args.dsn) as pg:
        with pg.cursor() as cur:
            print("Creating schema...")
            for stmt in _PG_SCHEMA:
                cur.execute(stmt)
            model_registry.ensure_schema(cur, dialect="postgres")
            for stmt in _INDEX_DDL:
                cur.execute(stmt)

            cur.execute("SELECT COUNT(*) FROM chat_messages")
            existing = cur.fetchone()[0]
            if existing and not args.force:
                print(f"ERROR: target already has {existing} chat_messages rows. "
                      f"Re-run with --force to truncate and re-copy.")
                return 3
            if args.force:
                print("Truncating target tables (--force)...")
                cur.execute("TRUNCATE " + ", ".join(present))
            else:
                # The API seeds model_lookup/model_version on every startup
                # (ChatLogger init), so these may be non-empty even on a fresh
                # target — copying over them would hit UNIQUE(name). Start them
                # clean ONLY when the source actually carries them (so their
                # original ids, referenced by chat_messages.model_version_id,
                # win); otherwise leave the API-seeded registry in place.
                registry = [t for t in ("model_lookup", "model_version") if t in present]
                if registry:
                    cur.execute("TRUNCATE " + ", ".join(registry))

            print("Copying data...")
            for table in present:
                copy_table(sq, cur, table, args.batch)
                fix_sequence(cur, table)

            print("Verifying...")
            # Materialize the list so EVERY table gets verified and printed,
            # even after the first mismatch (all() on a genexp short-circuits).
            results = [verify(sq, cur, t) for t in present]
            all_ok = all(results)

        if all_ok:
            pg.commit()
        else:
            pg.rollback()

    sq.close()
    if all_ok:
        print("Migration complete - all tables verified and committed.")
        return 0
    print("Migration FAILED verification - transaction rolled back; "
          "the Postgres data was NOT modified.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
