"""Per-intent source grounding — every curated intent cites its official source.

The intent tiers (Naive Bayes / Neural Network / intent retrieval) serve
curated responses with no provenance. This module binds each intent to the
official document that backs it — a Citizens' Charter page or an official-site
URL — so the /chat envelope layer can append a citation line to the reply and
fill ChatResponse.sources, the same way the charter/site RAG tiers already
cite their passages.

Bindings live in data/intent_sources.json, keyed by intent tag:

    {"bindings": {"admissions_requirements": [
        {"kind": "charter", "locator": "12", "label": "...", "score": 0.31},
        {"kind": "site", "locator": "http://...", "label": "Admissions", "score": 0.22}
    ]}}

The file is generated by scripts/bind_intent_sources.py (TF-IDF retrieval over
the same corpora charter_rag / site_rag index) and then reviewed — bindings
are deliberately NOT computed at serve time, so a citation can never point at
a passage that merely won a cosine ranking on one phrasing. Conversational
intents (greeting, thanks, …) stay unbound and get no citation.

Deliberately a standalone file rather than an intents-DB table: load_intents()
rebuilds cavsu_intents.db from the JSON (os.remove + recreate) whenever the
two drift, which would silently drop any extra table.

Env:
    INTENT_GROUNDING_ENABLED — "0" disables citations (default "1")
    INTENT_GROUNDING_PATH    — override the bindings file location
"""
from __future__ import annotations

import json
import logging
import os
from collections import defaultdict
from dataclasses import dataclass
from typing import Optional

_logger = logging.getLogger("diwa.intent_grounding")

_ENABLED = os.environ.get("INTENT_GROUNDING_ENABLED", "1") == "1"
_DEFAULT_PATH = os.path.join(
	os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
	"data", "intent_sources.json",
)
_PATH = os.environ.get("INTENT_GROUNDING_PATH", _DEFAULT_PATH)

# At most one charter + one site citation per reply — more reads as clutter.
_MAX_REFS_SHOWN = 2

# ── Binding derivation ───────────────────────────────────────────────────────
# Shared by scripts/bind_intent_sources.py (to PROPOSE bindings) and by
# check_drift (to ask "would the binder, re-run today, still pick this
# source?"). Keeping both on one code path is what makes the drift check
# exact instead of merely correlated.

# Aggregated-score floors. Aggregation sums the coverage-weighted scores of an
# intent's top passages per page/URL, so these sit above the single-passage
# AUGMENT floors in charter_rag (0.08) / site_rag (0.10).
CHARTER_MIN = 0.10
SITE_MIN = 0.12

# Conversational / meta intents — no official document backs "hello", and
# refusal/disambiguation replies must not carry a citation.
EXCLUDED_TAGS = frozenset({
	"greeting", "goodbye", "thanks", "chitchat", "nlu_fallback",
	"out_of_scope", "off_topic_homework", "compare_to_other_school",
	"id_verification_disambiguation", "verify_against_official",
})


def build_query(intent: dict) -> str:
	"""Retrieval query for an intent: how users ask it (patterns) plus what the
	curated answer says (responses) — the answers were written FROM these
	sources, so they are the strongest lexical bridge back to them."""
	parts = list(intent.get("patterns", [])[:12])
	parts += intent.get("responses", [])[:2]
	if intent.get("description"):
		parts.append(intent["description"])
	return " ".join(parts)[:2000]


def _aggregate(passages, key_fn, label_fn):
	"""Sum passage scores per page/URL; return the winner as a ref dict."""
	totals: dict[str, float] = defaultdict(float)
	meta: dict[str, tuple] = {}
	for p in passages:
		key = key_fn(p)
		totals[key] += p.score
		if key not in meta or p.score > meta[key][1]:
			meta[key] = (label_fn(p), p.score, p.text[:300])
	if not totals:
		return None
	locator = max(totals, key=totals.get)
	label, _, evidence = meta[locator]
	return {"locator": locator, "label": label,
	        "score": round(totals[locator], 4), "evidence": evidence}


def propose_for(intent: dict) -> dict:
	"""Best charter/site refs for one intent, above the floors. {} when none.

	Returns {"charter": {kind, locator, label, score, evidence}, "site": {...}}.
	"""
	from . import charter_rag, site_rag

	if intent.get("tag") in EXCLUDED_TAGS or not intent.get("active", True):
		return {}
	query = build_query(intent)
	if not query.strip():
		return {}
	out: dict[str, dict] = {}
	charter = charter_rag.get_index()
	if charter is not None:
		best = _aggregate(
			charter.retrieve(query, k=5),
			key_fn=lambda p: str(p.page), label_fn=lambda p: "",
		)
		if best and best["score"] >= CHARTER_MIN:
			out["charter"] = {"kind": "charter", **best}
	site = site_rag.get_index()
	if site is not None:
		best = _aggregate(
			site.retrieve(query, k=5),
			key_fn=lambda p: p.url, label_fn=lambda p: p.title,
		)
		if best and best["score"] >= SITE_MIN:
			out["site"] = {"kind": "site", **best}
	return out


@dataclass(frozen=True)
class SourceRef:
	kind: str      # "charter" | "site"
	locator: str   # charter page number, or site URL
	label: str = ""
	score: float = 0.0

	def citation(self) -> str:
		if self.kind == "charter":
			# Mirrors charter_rag.Passage.citation() so both tiers cite alike.
			return f"CvSU Citizens' Charter, FY 2026 edition, p. {self.locator}"
		title = f"“{self.label}” — " if self.label else ""
		return f"{title}official CvSU site ({self.locator})"


class GroundingIndex:
	def __init__(self, path: str = _PATH):
		self._bindings: dict[str, list[SourceRef]] = {}
		try:
			with open(path, encoding="utf-8") as fh:
				raw = json.load(fh)
		except (OSError, ValueError) as exc:
			_logger.warning("intent sources not readable (%s) — grounding disabled", exc)
			return
		for tag, refs in (raw.get("bindings") or {}).items():
			parsed = []
			for ref in refs:
				kind, locator = ref.get("kind"), str(ref.get("locator", "")).strip()
				if kind not in ("charter", "site") or not locator:
					continue
				parsed.append(SourceRef(
					kind=kind, locator=locator,
					label=ref.get("label") or "",
					score=float(ref.get("score") or 0.0),
				))
			if parsed:
				self._bindings[tag] = parsed
		_logger.info("intent grounding ready: %d bound intents", len(self._bindings))

	@property
	def available(self) -> bool:
		return bool(self._bindings)

	def refs_for(self, intent: Optional[str]) -> list[SourceRef]:
		"""Best-first source refs for an intent — at most one per source kind."""
		refs = sorted(
			self._bindings.get(intent or "", []),
			key=lambda r: r.score, reverse=True,
		)
		picked, kinds_seen = [], set()
		for ref in refs:
			if ref.kind in kinds_seen:
				continue
			picked.append(ref)
			kinds_seen.add(ref.kind)
			if len(picked) >= _MAX_REFS_SHOWN:
				break
		return picked

	def snapshot(self) -> dict:
		"""Operational summary for /admin/status."""
		kinds: dict[str, int] = {}
		for refs in self._bindings.values():
			for ref in refs:
				kinds[ref.kind] = kinds.get(ref.kind, 0) + 1
		return {
			"available": self.available,
			"bound_intents": len(self._bindings),
			"refs_by_kind": kinds,
		}


_index: Optional[GroundingIndex] = None


def get_index() -> Optional[GroundingIndex]:
	"""Lazy singleton; returns None when disabled or the bindings are missing."""
	global _index
	if not _ENABLED:
		return None
	if _index is None:
		_index = GroundingIndex()
	return _index if _index.available else None


def reload_index() -> Optional[GroundingIndex]:
	"""Drop the singleton and rebuild from the bindings file."""
	global _index
	_index = None
	return get_index()


def citation_block(refs: list[SourceRef]) -> str:
	"""Text appended to a curated reply — one 'Source:' line per ref."""
	if not refs:
		return ""
	label = "Source" if len(refs) == 1 else "Sources"
	lines = "\n".join(f"• {r.citation()}" for r in refs) if len(refs) > 1 \
		else refs[0].citation()
	sep = "\n" if len(refs) > 1 else " "
	return f"\n\n📖 {label}:{sep}{lines}"


def check_drift(intents: list[dict]) -> dict:
	"""Would the binder, re-run today, still pick each bound source?

	Re-derives each bound intent's best source with propose_for() — the same
	code path that produced the binding — and compares the locator. A mismatch
	means the corpus moved under the binding (charter re-OCR'd, site re-synced)
	and the citation may now point at the wrong page: re-run the binder and
	re-verify. A `stale` entry is one whose locator no longer exists in the
	corpus at all, which is strictly worse than a mismatch.

	Offline/admin use only — never called on the chat path.
	"""
	index = get_index()
	if index is None:
		return {"available": False, "checked": 0, "drifted": [], "stale": []}
	by_tag = {i["tag"]: i for i in intents if i.get("tag")}
	drifted, stale, checked = [], [], 0
	for tag, refs in index._bindings.items():
		intent = by_tag.get(tag)
		if intent is None:
			stale.append({"intent": tag, "reason": "intent no longer exists"})
			continue
		fresh = propose_for(intent)
		for ref in refs:
			checked += 1
			now = fresh.get(ref.kind)
			if now is None:
				drifted.append({
					"intent": tag, "kind": ref.kind, "bound": ref.locator,
					"now": None, "reason": "no longer scores above the floor",
				})
			elif now["locator"] != ref.locator:
				drifted.append({
					"intent": tag, "kind": ref.kind, "bound": ref.locator,
					"now": now["locator"], "reason": "binder would now pick a different source",
				})
	return {
		"available": True, "checked": checked,
		"drifted": drifted, "stale": stale,
	}
