"""
Chat Logging System for CvSU Chatbot
Logs all conversations, intents, and metadata to files and database.

Backend selection (same public interface on both):
- DATABASE_URL unset            -> stdlib sqlite3 at db_path (default logs/chat_history.db)
- DATABASE_URL=postgresql://... -> PostgreSQL via psycopg v3

Timestamps are stored as TEXT ISO-8601 strings on BOTH backends: lexical
order equals chronological order, existing SQLite data copies over 1:1, and
every date query stays portable (substr/lexical compare instead of
SQLite-only DATE()/strftime()).
"""

import json
import os
import re
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, List, Dict
import threading

try:
    from . import model_registry
except ImportError:  # imported as a top-level module (scripts, tests)
    import model_registry

try:
    from . import pii as _pii
except ImportError:  # imported as a top-level module (scripts, tests)
    import pii as _pii

try:  # psycopg is only needed when DATABASE_URL points at Postgres
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - sqlite-only environments
    psycopg = None
    dict_row = None


def _clamp_limit(limit, default: int, cap: int) -> int:
    """Bound a caller-supplied row limit before it reaches `LIMIT ?`.

    SQLite treats a NEGATIVE limit as *unlimited*, so an unclamped `limit=-1`
    on any retrieval method is a full-table dump (and an OOM on a large DB).
    Clamped here rather than only at the API layer because these methods are
    also called directly by scripts, the exporter, and the retention loop.
    A non-numeric value falls back to the method's own default.
    """
    try:
        limit = int(limit)
    except (TypeError, ValueError):
        return default
    return max(1, min(limit, cap))


# Filenames derived from a user id must not be able to escape log_dir:
# on Windows an encoded backslash ("a%5C..%5Cb") survives the URL path decode
# and would otherwise write outside the log directory.
_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9_.-]{1,64}$")


def is_safe_user_id(user_id: str) -> bool:
    """True if `user_id` is safe to embed in a filename (allowlist + no '..')."""
    if not isinstance(user_id, str) or not _SAFE_ID_RE.match(user_id):
        return False
    return ".." not in user_id


# Postgres DDL. Mirrors the SQLite schema below, with three deliberate choices:
# - GENERATED BY DEFAULT AS IDENTITY (not ALWAYS) so the sqlite->pg migration
#   script can insert rows with their original ids.
# - helpful stays SMALLINT 0/1 (not BOOLEAN) so AVG(helpful) and the
#   int(helpful)/bool(row) round-trips in this file keep working unchanged.
# - NO foreign keys: SQLite never enforced them (PRAGMA foreign_keys was never
#   set on these connections), and cleanup_old_logs deletes chat_messages that
#   feedback rows may reference. Enforcing FKs now would start rejecting
#   legitimate writes. Indexes stand in for the lookup paths instead.
_PG_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS chat_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp TEXT NOT NULL,
        user_id TEXT NOT NULL,
        session_id TEXT,
        user_message TEXT NOT NULL,
        bot_response TEXT NOT NULL,
        intent TEXT NOT NULL,
        confidence DOUBLE PRECISION NOT NULL,
        response_time_ms DOUBLE PRECISION,
        model_used TEXT,
        model_version_id BIGINT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id TEXT UNIQUE NOT NULL,
        user_id TEXT NOT NULL,
        start_time TEXT NOT NULL,
        end_time TEXT,
        message_count INTEGER DEFAULT 0,
        average_confidence DOUBLE PRECISION
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS intent_stats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        intent TEXT UNIQUE NOT NULL,
        count INTEGER DEFAULT 0,
        avg_confidence DOUBLE PRECISION,
        last_used TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS feedback (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp TEXT NOT NULL,
        message_id BIGINT,
        user_id TEXT,
        session_id TEXT,
        intent TEXT,
        rating INTEGER CHECK(rating BETWEEN 1 AND 5),
        helpful SMALLINT CHECK(helpful IN (0, 1)),
        reason TEXT,
        comment TEXT,
        suggested_intent TEXT,
        user_message TEXT
    )
    """,
]

# Same syntax works on both backends.
_INDEX_DDL = [
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_timestamp ON chat_messages (timestamp)",
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_user_id ON chat_messages (user_id)",
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages (session_id)",
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_intent ON chat_messages (intent)",
    "CREATE INDEX IF NOT EXISTS idx_feedback_timestamp ON feedback (timestamp)",
    "CREATE INDEX IF NOT EXISTS idx_feedback_message_id ON feedback (message_id)",
]


class ChatLogger:
    """Handles all chat logging operations"""

    def __init__(
        self,
        log_dir: str = "logs",
        db_path: str = "logs/chat_history.db",
        database_url: Optional[str] = None,
    ):
        self.log_dir = Path(log_dir)
        self.db_path = db_path
        self.lock = threading.Lock()
        # name -> current model_version.id, populated by the registry sync.
        self.model_versions: Dict[str, int] = {}

        url = database_url if database_url is not None else os.getenv("DATABASE_URL")
        self.database_url = url or None
        self.is_pg = bool(
            self.database_url
            and self.database_url.startswith(("postgres://", "postgresql://"))
        )
        if self.database_url and not self.is_pg:
            raise ValueError(
                "Unsupported DATABASE_URL scheme "
                f"'{self.database_url.split(':', 1)[0]}' - expected postgresql://"
            )
        if self.is_pg and psycopg is None:
            raise RuntimeError(
                "DATABASE_URL points at Postgres but psycopg is not installed. "
                "Run: pip install 'psycopg[binary]'"
            )

        # Create directories
        self.log_dir.mkdir(exist_ok=True)

        # Initialize database
        self._init_database()

        print(f"[OK] Chat Logger initialized")
        print(f"  Logs directory: {self.log_dir}")
        if self.is_pg:
            print(f"  Database: PostgreSQL ({self._redacted_url()})")
        else:
            print(f"  Database: {self.db_path}")

    def _redacted_url(self) -> str:
        """DATABASE_URL with the password hidden, for logs."""
        url = self.database_url or ""
        if "@" in url and "://" in url:
            scheme, rest = url.split("://", 1)
            creds, host = rest.rsplit("@", 1)
            user = creds.split(":", 1)[0]
            return f"{scheme}://{user}:***@{host}"
        return url

    # ========== Backend plumbing ==========

    def _connect(self, dicts: bool = False):
        """Open a connection + cursor. dicts=True yields mapping-style rows."""
        if self.is_pg:
            # connect_timeout bounds a Postgres stall/partition to seconds —
            # these connects run on the request path, and libpq's default is
            # to wait on TCP indefinitely (minutes on a black-holed host).
            conn = psycopg.connect(self.database_url, connect_timeout=5)
            cursor = conn.cursor(row_factory=dict_row) if dicts else conn.cursor()
        else:
            conn = sqlite3.connect(self.db_path)
            # WAL lets readers proceed during a write (the retention sweep and
            # /admin reads no longer collide with /chat inserts); busy_timeout
            # makes a would-be writer wait rather than raise "database is
            # locked". Together with self.lock on the write paths this keeps the
            # single shared DB file race-free under the async server.
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA busy_timeout=5000")
            if dicts:
                conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
        return conn, cursor

    def _sql(self, query: str) -> str:
        """Translate qmark placeholders for psycopg. Safe here because no
        query in this module contains a literal '?' character."""
        return query.replace("?", "%s") if self.is_pg else query

    def _insert_returning_id(self, cursor, query: str, params) -> Optional[int]:
        """INSERT and return the new row id (RETURNING on PG, lastrowid on SQLite)."""
        if self.is_pg:
            cursor.execute(self._sql(query) + " RETURNING id", params)
            row = cursor.fetchone()
            return row[0] if row else None
        cursor.execute(query, params)
        return cursor.lastrowid

    def _init_database(self):
        """Initialize the chat-history schema (idempotent, both backends)."""
        try:
            if self.is_pg:
                self._init_postgres()
            else:
                self._init_sqlite()
        except Exception as e:
            print(f"[ERROR] Database initialization error: {e}")

    def _init_postgres(self):
        conn, cursor = self._connect()
        try:
            for statement in _PG_SCHEMA:
                cursor.execute(statement)
            # Legacy-column migrations (same shape as the SQLite ALTERs below).
            cursor.execute("ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS model_used TEXT")
            cursor.execute("ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS model_version_id BIGINT")
            cursor.execute("ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_message TEXT")
            cursor.execute("ALTER TABLE feedback ADD COLUMN IF NOT EXISTS reason TEXT")
            for statement in _INDEX_DDL:
                cursor.execute(statement)
            # Commit the schema BEFORE the registry sync: on Postgres an SQL
            # error inside sync() would abort the shared transaction, and the
            # later commit would silently roll back all of the DDL above.
            conn.commit()

            try:
                self.model_versions = model_registry.sync(cursor, dialect="postgres")
                conn.commit()
            except Exception as e:
                conn.rollback()
                print(f"[ERROR] Model registry sync failed: {e}")
        finally:
            conn.close()

    def _init_sqlite(self):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Chat messages table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS chat_messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                user_id TEXT NOT NULL,
                session_id TEXT,
                user_message TEXT NOT NULL,
                bot_response TEXT NOT NULL,
                intent TEXT NOT NULL,
                confidence REAL NOT NULL,
                response_time_ms REAL,
                model_used TEXT
            )
        """)

        # Ensure legacy DBs have the new columns
        cursor.execute("PRAGMA table_info(chat_messages)")
        existing_columns = [row[1] for row in cursor.fetchall()]
        if "model_used" not in existing_columns:
            cursor.execute("ALTER TABLE chat_messages ADD COLUMN model_used TEXT")
        if "model_version_id" not in existing_columns:
            cursor.execute(
                "ALTER TABLE chat_messages ADD COLUMN model_version_id INTEGER "
                "REFERENCES model_version(id)"
            )

        # Onboard the model fixture: seed model_lookup and register the
        # current version of each model (new row when an artifact changed).
        try:
            self.model_versions = model_registry.sync(cursor, dialect="sqlite")
        except Exception as e:
            print(f"[ERROR] Model registry sync failed: {e}")

        # User sessions table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT UNIQUE NOT NULL,
                user_id TEXT NOT NULL,
                start_time TEXT NOT NULL,
                end_time TEXT,
                message_count INTEGER DEFAULT 0,
                average_confidence REAL
            )
        """)

        # Intent statistics table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS intent_stats (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                intent TEXT UNIQUE NOT NULL,
                count INTEGER DEFAULT 0,
                avg_confidence REAL,
                last_used TEXT
            )
        """)

        # User feedback table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS feedback (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp TEXT NOT NULL,
                message_id INTEGER,
                user_id TEXT,
                session_id TEXT,
                intent TEXT,
                rating INTEGER CHECK(rating BETWEEN 1 AND 5),
                helpful INTEGER CHECK(helpful IN (0, 1)),
                reason TEXT,
                comment TEXT,
                suggested_intent TEXT,
                user_message TEXT,
                FOREIGN KEY (message_id) REFERENCES chat_messages(id)
            )
        """)

        # Idempotent migrations for older DBs
        cursor.execute("PRAGMA table_info(feedback)")
        fb_cols = [r[1] for r in cursor.fetchall()]
        if "user_message" not in fb_cols:
            cursor.execute("ALTER TABLE feedback ADD COLUMN user_message TEXT")
        if "reason" not in fb_cols:
            cursor.execute("ALTER TABLE feedback ADD COLUMN reason TEXT")

        for statement in _INDEX_DDL:
            cursor.execute(statement)

        conn.commit()
        conn.close()

    def log_chat(
        self,
        user_id: str,
        user_message: str,
        bot_response: str,
        intent: str,
        confidence: float,
        model_used: Optional[str] = None,
        session_id: Optional[str] = None,
        response_time_ms: Optional[float] = None
    ) -> Optional[int]:
        """
        Log a single chat message to database and file

        Args:
            user_id: User identifier
            user_message: User's input
            bot_response: Bot's response
            intent: Classified intent
            confidence: Confidence score (0-1)
            session_id: Optional session identifier
            response_time_ms: Optional response time in milliseconds

        Returns:
            int: The new chat_messages row ID, or None on failure
        """
        try:
            timestamp = datetime.now().isoformat()
            message_id = None

            # Minimize by design: mask volunteered PII (student numbers, emails,
            # phone numbers) BEFORE it is persisted to the DB and the daily file.
            # Masking happens only here at the logging boundary — the live
            # message the brain already answered is never touched. See api/pii.py.
            user_message = _pii.mask_pii(user_message)

            with self.lock:
                # Log to database
                message_id = self._log_to_db(
                    timestamp, user_id, session_id, user_message,
                    bot_response, intent, confidence, model_used, response_time_ms
                )

                # Log to file
                self._log_to_file(
                    timestamp, user_id, session_id, user_message,
                    bot_response, intent, confidence, model_used
                )

                # Update intent statistics
                self._update_intent_stats(intent, confidence, timestamp)

                # Update session stats
                if session_id:
                    self._update_session_stats(session_id, user_id, timestamp)

            return message_id
        except Exception as e:
            print(f"[ERROR] Error logging chat: {e}")
            return None

    def _log_to_db(
        self, timestamp, user_id, session_id, user_msg, bot_resp, intent, conf, model_used, resp_time
    ) -> Optional[int]:
        """Log to the database, returns the new row ID."""
        try:
            conn, cursor = self._connect()

            model_version_id = self.model_versions.get(model_registry.resolve(model_used))
            row_id = self._insert_returning_id(cursor, """
                INSERT INTO chat_messages
                (timestamp, user_id, session_id, user_message, bot_response, intent, confidence, model_used, model_version_id, response_time_ms)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (timestamp, user_id, session_id, user_msg, bot_resp, intent, conf, model_used, model_version_id, resp_time))

            conn.commit()
            conn.close()
            return row_id
        except Exception as e:
            print(f"[ERROR] Database log error: {e}")
            return None

    def _log_to_file(self, timestamp, user_id, session_id, user_msg, bot_resp, intent, conf, model_used=None):
        """Log to JSON file"""
        try:
            # Create daily log file
            date_str = datetime.now().strftime("%Y-%m-%d")
            log_file = self.log_dir / f"chat_{date_str}.log"

            log_entry = {
                "timestamp": timestamp,
                "user_id": user_id,
                "session_id": session_id,
                "user_message": user_msg,
                "bot_response": bot_resp,
                "intent": intent,
                "confidence": conf,
                "model_used": model_used
            }

            with open(log_file, "a", encoding="utf-8") as f:
                f.write(json.dumps(log_entry) + "\n")
        except Exception as e:
            print(f"[ERROR] File log error: {e}")

    def _update_intent_stats(self, intent: str, confidence: float, timestamp: str):
        """Update intent statistics"""
        try:
            conn, cursor = self._connect()

            # In ON CONFLICT ... DO UPDATE, unqualified column references
            # resolve to the existing row on both SQLite and Postgres.
            cursor.execute(self._sql("""
                INSERT INTO intent_stats (intent, count, avg_confidence, last_used)
                VALUES (?, 1, ?, ?)
                ON CONFLICT(intent) DO UPDATE SET
                    count = intent_stats.count + 1,
                    avg_confidence = (intent_stats.avg_confidence * (intent_stats.count - 1) + ?) / intent_stats.count,
                    last_used = ?
            """), (intent, confidence, timestamp, confidence, timestamp))

            conn.commit()
            conn.close()
        except Exception as e:
            print(f"[ERROR] Intent stats update error: {e}")

    def _update_session_stats(self, session_id: str, user_id: str, timestamp: str):
        """Update session statistics"""
        try:
            conn, cursor = self._connect()

            # Atomic upsert instead of the old check-then-insert, which races
            # under multi-worker Postgres. Semantics preserved: a brand-new
            # session starts at message_count 0 (the first message is not
            # counted — quirk kept for parity with the original).
            cursor.execute(self._sql("""
                INSERT INTO sessions (session_id, user_id, start_time)
                VALUES (?, ?, ?)
                ON CONFLICT(session_id) DO UPDATE SET
                    message_count = sessions.message_count + 1
            """), (session_id, user_id, timestamp))

            conn.commit()
            conn.close()
        except Exception as e:
            print(f"[ERROR] Session stats update error: {e}")

    # ========== Retrieval Methods ==========

    def get_user_history(self, user_id: str, limit: int = 50) -> List[Dict]:
        """Get chat history for a user"""
        try:
            limit = _clamp_limit(limit, 50, 1000)  # 1000 = export_user_data's ask
            conn, cursor = self._connect(dicts=True)

            cursor.execute(self._sql("""
                SELECT * FROM chat_messages
                WHERE user_id = ?
                ORDER BY timestamp DESC
                LIMIT ?
            """), (user_id, limit))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving user history: {e}")
            return []

    def get_recent_messages(self, limit: int = 20) -> List[Dict]:
        """Get the most recent chat messages across all users."""
        try:
            limit = _clamp_limit(limit, 20, 200)
            conn, cursor = self._connect(dicts=True)

            cursor.execute(self._sql("""
                SELECT * FROM chat_messages
                ORDER BY timestamp DESC
                LIMIT ?
            """), (limit,))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving recent messages: {e}")
            return []

    def get_session_history(self, session_id: str) -> List[Dict]:
        """Get all messages in a session"""
        try:
            conn, cursor = self._connect(dicts=True)

            cursor.execute(self._sql("""
                SELECT * FROM chat_messages
                WHERE session_id = ?
                ORDER BY timestamp ASC
            """), (session_id,))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving session history: {e}")
            return []

    def get_intent_statistics(self) -> List[Dict]:
        """Get statistics for all intents"""
        try:
            conn, cursor = self._connect(dicts=True)

            cursor.execute("""
                SELECT intent, count, avg_confidence, last_used
                FROM intent_stats
                ORDER BY count DESC
            """)

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving intent stats: {e}")
            return []

    def get_session_list(self, user_id: Optional[str] = None, limit: int = 20) -> List[Dict]:
        """Get list of sessions"""
        try:
            limit = _clamp_limit(limit, 20, 1000)
            conn, cursor = self._connect(dicts=True)

            if user_id:
                cursor.execute(self._sql("""
                    SELECT * FROM sessions
                    WHERE user_id = ?
                    ORDER BY start_time DESC
                    LIMIT ?
                """), (user_id, limit))
            else:
                cursor.execute(self._sql("""
                    SELECT * FROM sessions
                    ORDER BY start_time DESC
                    LIMIT ?
                """), (limit,))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving sessions: {e}")
            return []

    def get_today_stats(self) -> Dict:
        """Get today's chat statistics"""
        try:
            conn, cursor = self._connect()

            today = datetime.now().strftime("%Y-%m-%d")

            # substr(timestamp, 1, 10) is the ISO date prefix — portable
            # replacement for SQLite-only DATE(timestamp).
            cursor.execute(self._sql("""
                SELECT COUNT(*) FROM chat_messages
                WHERE substr(timestamp, 1, 10) = ?
            """), (today,))
            total_messages = cursor.fetchone()[0]

            # Unique users today
            cursor.execute(self._sql("""
                SELECT COUNT(DISTINCT user_id) FROM chat_messages
                WHERE substr(timestamp, 1, 10) = ?
            """), (today,))
            unique_users = cursor.fetchone()[0]

            # Average confidence today
            cursor.execute(self._sql("""
                SELECT AVG(confidence) FROM chat_messages
                WHERE substr(timestamp, 1, 10) = ?
            """), (today,))
            avg_confidence = cursor.fetchone()[0] or 0

            # Most used intent today
            cursor.execute(self._sql("""
                SELECT intent, COUNT(*) as count FROM chat_messages
                WHERE substr(timestamp, 1, 10) = ?
                GROUP BY intent
                ORDER BY count DESC
                LIMIT 1
            """), (today,))
            top_intent = cursor.fetchone()

            conn.close()

            return {
                "date": today,
                "total_messages": total_messages,
                "unique_users": unique_users,
                "average_confidence": round(float(avg_confidence), 4),
                "top_intent": {
                    "intent": top_intent[0],
                    "count": top_intent[1]
                } if top_intent else None
            }
        except Exception as e:
            print(f"[ERROR] Error getting daily stats: {e}")
            return {}

    def search_logs(self, query: str, limit: int = 20) -> List[Dict]:
        """Search logs by user message or bot response"""
        try:
            limit = _clamp_limit(limit, 20, 200)
            conn, cursor = self._connect(dicts=True)

            # LOWER() on both sides keeps the search case-insensitive on
            # Postgres too (SQLite LIKE is already case-insensitive for ASCII).
            search_term = f"%{query}%"
            cursor.execute(self._sql("""
                SELECT * FROM chat_messages
                WHERE LOWER(user_message) LIKE LOWER(?) OR LOWER(bot_response) LIKE LOWER(?)
                ORDER BY timestamp DESC
                LIMIT ?
            """), (search_term, search_term, limit))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error searching logs: {e}")
            return []

    def log_feedback(
        self,
        message_id: Optional[int],
        user_id: Optional[str],
        session_id: Optional[str],
        intent: Optional[str],
        rating: Optional[int],
        helpful: Optional[bool],
        comment: Optional[str],
        suggested_intent: Optional[str],
        user_message: Optional[str] = None,
        reason: Optional[str] = None,
    ) -> Optional[int]:
        """Log user feedback for a bot response. Returns the new feedback row ID."""
        try:
            timestamp = datetime.now().isoformat()
            helpful_int = int(helpful) if helpful is not None else None
            # Same minimization as the chat log: if a client sends the raw query
            # on the feedback record (used when message_id is unavailable), mask
            # any volunteered PII before it is stored on this sibling column.
            user_message = _pii.mask_pii(user_message) if user_message else user_message

            with self.lock:
                conn, cursor = self._connect()

                feedback_id = self._insert_returning_id(cursor, """
                    INSERT INTO feedback
                    (timestamp, message_id, user_id, session_id, intent, rating, helpful, reason, comment, suggested_intent, user_message)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (timestamp, message_id, user_id, session_id, intent,
                       rating, helpful_int, reason, comment, suggested_intent, user_message))

                conn.commit()
                conn.close()

            return feedback_id
        except Exception as e:
            print(f"[ERROR] Error logging feedback: {e}")
            return None

    def get_feedback_stats(self) -> Dict:
        """Aggregate feedback statistics: overall, per-intent, low-rated, and recent comments."""
        try:
            conn, cursor = self._connect()

            # Overall totals. float() coercions: Postgres returns Decimal for
            # AVG(integer)/AVG(smallint); SQLite returns float — normalize.
            cursor.execute("SELECT COUNT(*), AVG(rating), AVG(helpful) FROM feedback")
            row = cursor.fetchone()
            total = row[0] or 0
            avg_rating = round(float(row[1]), 2) if row[1] is not None else None
            helpful_pct = round(float(row[2]) * 100, 1) if row[2] is not None else None

            # Per-intent breakdown
            cursor.execute("""
                SELECT intent,
                       COUNT(*) AS feedback_count,
                       AVG(rating) AS avg_rating,
                       AVG(helpful) AS helpful_pct,
                       SUM(CASE WHEN helpful = 0 THEN 1 ELSE 0 END) AS unhelpful_count
                FROM feedback
                WHERE intent IS NOT NULL
                GROUP BY intent
                ORDER BY feedback_count DESC
            """)
            by_intent = [
                {
                    "intent": r[0],
                    "feedback_count": r[1],
                    "avg_rating": round(float(r[2]), 2) if r[2] is not None else None,
                    "helpful_pct": round(float(r[3]) * 100, 1) if r[3] is not None else None,
                    "unhelpful_count": r[4]
                }
                for r in cursor.fetchall()
            ]

            # Lowest-rated intents (min 3 ratings). HAVING repeats COUNT(*)
            # because Postgres does not allow SELECT aliases in HAVING.
            cursor.execute("""
                SELECT intent, AVG(rating) AS avg_r, COUNT(*) AS cnt
                FROM feedback
                WHERE rating IS NOT NULL AND intent IS NOT NULL
                GROUP BY intent
                HAVING COUNT(*) >= 3
                ORDER BY avg_r ASC
                LIMIT 5
            """)
            low_rated = [
                {"intent": r[0], "avg_rating": round(float(r[1]), 2), "count": r[2]}
                for r in cursor.fetchall()
            ]

            # Recent comments
            cursor.execute("""
                SELECT timestamp, intent, rating, helpful, reason, comment, suggested_intent
                FROM feedback
                WHERE comment IS NOT NULL AND TRIM(comment) != ''
                ORDER BY timestamp DESC
                LIMIT 10
            """)
            recent_comments = [
                {
                    "timestamp": r[0],
                    "intent": r[1],
                    "rating": r[2],
                    "helpful": bool(r[3]) if r[3] is not None else None,
                    "reason": r[4],
                    "comment": r[5],
                    "suggested_intent": r[6]
                }
                for r in cursor.fetchall()
            ]

            # Reason-code breakdown (overall + split by thumbs direction)
            cursor.execute("""
                SELECT reason,
                       helpful,
                       COUNT(*) AS cnt
                FROM feedback
                WHERE reason IS NOT NULL AND TRIM(reason) != ''
                GROUP BY reason, helpful
                ORDER BY cnt DESC
            """)
            reason_rows = cursor.fetchall()
            by_reason = []
            for r in reason_rows:
                by_reason.append({
                    "reason": r[0],
                    "helpful": bool(r[1]) if r[1] is not None else None,
                    "count": r[2]
                })

            conn.close()

            return {
                "total_feedback": total,
                "avg_rating": avg_rating,
                "helpful_pct": helpful_pct,
                "by_intent": by_intent,
                "low_rated_intents": low_rated,
                "recent_comments": recent_comments,
                "by_reason": by_reason
            }
        except Exception as e:
            print(f"[ERROR] Error getting feedback stats: {e}")
            return {}

    def get_feedback_entries(
        self,
        limit: int = 100,
        helpful: Optional[bool] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        intent: Optional[str] = None,
        min_rating: Optional[int] = None,
        max_rating: Optional[int] = None
    ) -> List[Dict]:
        """Return feedback rows joined with their source chat message when available."""
        try:
            limit = _clamp_limit(limit, 100, 1000)
            conn, cursor = self._connect(dicts=True)

            where_clauses = []
            params = []

            if helpful is not None:
                where_clauses.append("f.helpful = ?")
                params.append(int(helpful))
            if user_id:
                where_clauses.append("f.user_id = ?")
                params.append(user_id)
            if session_id:
                where_clauses.append("f.session_id = ?")
                params.append(session_id)
            if intent:
                where_clauses.append("f.intent = ?")
                params.append(intent)
            if min_rating is not None:
                where_clauses.append("f.rating >= ?")
                params.append(min_rating)
            if max_rating is not None:
                where_clauses.append("f.rating <= ?")
                params.append(max_rating)

            where_sql = ""
            if where_clauses:
                where_sql = "WHERE " + " AND ".join(where_clauses)

            cursor.execute(self._sql(f"""
                SELECT
                    f.id,
                    f.timestamp,
                    f.message_id,
                    f.user_id,
                    f.session_id,
                    f.intent,
                    f.rating,
                    f.helpful,
                    f.reason,
                    f.comment,
                    f.suggested_intent,
                    COALESCE(m.user_message, f.user_message) AS user_message,
                    m.bot_response,
                    m.confidence AS message_confidence,
                    m.model_used
                FROM feedback f
                LEFT JOIN chat_messages m ON f.message_id = m.id
                {where_sql}
                ORDER BY f.timestamp DESC
                LIMIT ?
            """), (*params, limit))

            rows = cursor.fetchall()
            conn.close()

            results = []
            for row in rows:
                item = dict(row)
                if item["helpful"] is not None:
                    item["helpful"] = bool(item["helpful"])
                results.append(item)

            return results
        except Exception as e:
            print(f"[ERROR] Error retrieving feedback entries: {e}")
            return []

    def get_fallback_examples(self, limit: int = 100) -> List[Dict]:
        """Get recent fallback user utterances and metadata."""
        try:
            limit = _clamp_limit(limit, 100, 1000)
            conn, cursor = self._connect(dicts=True)

            cursor.execute(self._sql("""
                SELECT user_message, bot_response, timestamp, user_id, session_id, confidence, model_used
                FROM chat_messages
                WHERE intent = 'nlu_fallback'
                ORDER BY timestamp DESC
                LIMIT ?
            """), (limit,))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving fallback examples: {e}")
            return []

    def get_anti_pattern_rows(
        self,
        days: int = 30,
        limit: int = 2000,
        low_conf_threshold: float = 0.5,
    ) -> List[Dict]:
        """Rows relevant to anti-pattern mining within the retention window:
        unanswered fallbacks, off-topic / homework / comparison refusals, every
        safety trip, and low-confidence answers. Fed to
        anti_patterns.build_report(). Messages are already PII-masked at write
        time. The safety-intent match is a BOUND LIKE parameter, not a literal:
        a literal '%' in the SQL text raises in psycopg (which reserves
        %s/%b/%t), so 'safety_%' must travel in the params to stay portable
        across SQLite and Postgres."""
        try:
            # days is also bounded (a huge value overflows timedelta; a
            # negative one puts the window in the future and returns nothing).
            days = _clamp_limit(days, 30, 3650)
            limit = _clamp_limit(limit, 2000, 5000)
            conn, cursor = self._connect(dicts=True)

            cutoff = (datetime.now() - timedelta(days=days)).isoformat()
            cursor.execute(self._sql("""
                SELECT user_message, intent, confidence, timestamp, model_used
                FROM chat_messages
                WHERE timestamp >= ?
                  AND (
                    intent IN ('nlu_fallback', 'fallback', 'out_of_scope',
                               'off_topic_homework', 'compare_to_other_school')
                    OR intent LIKE ?
                    OR confidence < ?
                  )
                ORDER BY timestamp DESC
                LIMIT ?
            """), (cutoff, "safety_%", low_conf_threshold, limit))

            rows = cursor.fetchall()
            conn.close()

            return [dict(row) for row in rows]
        except Exception as e:
            print(f"[ERROR] Error retrieving anti-pattern rows: {e}")
            return []

    def export_user_data(self, user_id: str) -> Optional[str]:
        """Export all data for a user as JSON.

        `user_id` becomes part of the output FILENAME, so it is allowlisted
        before anything is written — an id like `..%5C..%5Cwww/index` would
        otherwise place an attacker-shaped JSON file anywhere the process can
        write. Returns None when the id is rejected.
        """
        try:
            if not is_safe_user_id(user_id):
                print(f"[ERROR] Export refused: unsafe user_id {user_id!r}")
                return None

            history = self.get_user_history(user_id, limit=1000)
            sessions = self.get_session_list(user_id, limit=100)

            export_data = {
                "user_id": user_id,
                "export_date": datetime.now().isoformat(),
                "message_count": len(history),
                "session_count": len(sessions),
                "messages": history,
                "sessions": sessions
            }

            # Save to file — second gate: the resolved path must still sit
            # directly inside log_dir after the OS has had its say.
            filename = (self.log_dir / f"export_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json").resolve()
            if filename.parent != self.log_dir.resolve():
                print("[ERROR] Export refused: path escapes the log directory")
                return None
            with open(filename, "w", encoding="utf-8") as f:
                json.dump(export_data, f, indent=2, ensure_ascii=False)

            return str(filename)
        except Exception as e:
            print(f"[ERROR] Error exporting user data: {e}")
            return None

    def cleanup_old_logs(self, days: int = 30):
        """Enforce the retention window: delete chat_messages AND feedback rows
        older than `days`, and prune the daily chat_*.log files past the same
        cutoff. Runs under self.lock so the DELETE serializes with the writer
        paths (log_chat / log_feedback) on the shared SQLite file instead of
        racing them on a second connection."""
        try:
            # Retention is DESTRUCTIVE, so `days` is clamped to at least 1 and
            # the cutoff is asserted to be in the past before the DELETE runs.
            # Without this, days <= 0 puts the cutoff in the FUTURE and
            # `timestamp < cutoff` matches every row — wiping the entire chat +
            # feedback history and every daily log file.
            days = _clamp_limit(days, 30, 3650)

            # ISO-8601 strings compare lexically in chronological order, so a
            # plain < against the cutoff ISO string is portable — replaces the
            # SQLite-only strftime('%s', timestamp) epoch comparison.
            # timedelta (not epoch math): fromtimestamp() rejects pre-1970
            # values on Windows, which a large `days` would produce.
            now = datetime.now()
            cutoff = now - timedelta(days=days)
            if cutoff >= now:  # unreachable after the clamp; belt and braces
                print("[ERROR] Retention refused: cutoff is not in the past")
                return 0
            cutoff_iso = cutoff.isoformat()

            with self.lock:
                conn, cursor = self._connect()
                cursor.execute(self._sql(
                    "DELETE FROM chat_messages WHERE timestamp < ?"), (cutoff_iso,))
                deleted = cursor.rowcount
                # feedback rows carry user_id / session_id / free-text comment —
                # purge them on the same window so nothing outlives the policy.
                try:
                    cursor.execute(self._sql(
                        "DELETE FROM feedback WHERE timestamp < ?"), (cutoff_iso,))
                except Exception:  # very old DBs may lack the table
                    pass
                conn.commit()
                conn.close()

            # Prune the daily JSON log files (chat_YYYY-MM-DD.log) — they hold a
            # (masked) copy of every turn and would otherwise accumulate forever.
            purged_files = 0
            cutoff_date = cutoff.strftime("%Y-%m-%d")
            for f in self.log_dir.glob("chat_*.log"):
                date_part = f.stem[len("chat_"):]
                if len(date_part) == 10 and date_part < cutoff_date:
                    try:
                        f.unlink()
                        purged_files += 1
                    except OSError:
                        pass

            print(f"[OK] Retention: deleted {deleted} chat rows, "
                  f"purged {purged_files} old log file(s)")
            return deleted
        except Exception as e:
            print(f"[ERROR] Error cleaning logs: {e}")
            return 0
