"""
Model lookup + version registry for chat logging.

On startup ("onboarding") the fixture at data/fixtures/model_lookup.json is
synced into the `model_lookup` table, and a `model_version` row is created for
each model whenever its fingerprint changes — artifact-backed models (NB / NN /
charter corpus) are fingerprinted by file hash, LLMs by their configured model
id, and code-level gates/bridges by the code version constant. Chat rows then
reference the version that answered (chat_messages.model_version_id), so a
retrain or model swap is traceable in the history.
"""

import hashlib
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

_REPO_ROOT = Path(__file__).resolve().parent.parent
_FIXTURE_PATH = _REPO_ROOT / "data" / "fixtures" / "model_lookup.json"

# Bumping this re-versions the code-level entries (gates, bridges) that have
# no artifact or env-configured model id to fingerprint.
CODE_VERSION = "1"


def ensure_schema(cursor, dialect: str = "sqlite") -> None:
    """Create the registry tables. `cursor` may be a sqlite3 or psycopg cursor;
    `dialect` picks the DDL flavor ("sqlite" or "postgres")."""
    if dialect == "postgres":
        pk = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        fk_type = "BIGINT"
    else:
        pk = "INTEGER PRIMARY KEY AUTOINCREMENT"
        fk_type = "INTEGER"
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS model_lookup (
            id {pk},
            name TEXT UNIQUE NOT NULL,
            display_name TEXT,
            kind TEXT
        )
    """)
    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS model_version (
            id {pk},
            model_id {fk_type} NOT NULL REFERENCES model_lookup(id),
            version_label TEXT NOT NULL,
            fingerprint TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(model_id, fingerprint)
        )
    """)


def _fingerprint(entry: dict) -> tuple:
    """(fingerprint, version_label) for a fixture entry."""
    artifacts = entry.get("artifacts") or []
    if artifacts:
        digest = hashlib.sha256()
        for rel in artifacts:
            path = _REPO_ROOT / rel
            digest.update(rel.encode())
            if path.exists():
                digest.update(path.read_bytes())
            else:
                digest.update(b"<missing>")
        fp = digest.hexdigest()
        return fp, fp[:12]
    env_name = entry.get("version_env")
    if env_name:
        value = os.getenv(env_name) or entry.get("version_default") or "unset"
        return f"env:{env_name}={value}", value
    return f"code:{CODE_VERSION}", f"code-v{CODE_VERSION}"


def sync(cursor, dialect: str = "sqlite") -> Dict[str, int]:
    """Seed model_lookup from the fixture and register the current version of
    each model (new row only when the fingerprint changed). Returns the
    {model name -> current model_version.id} map used when logging chats.

    `cursor` may be a sqlite3 or psycopg cursor; `dialect` selects the DDL
    flavor and placeholder style. All statements use portable upsert syntax
    (ON CONFLICT works on SQLite >= 3.24 and Postgres alike)."""
    q = (lambda s: s.replace("?", "%s")) if dialect == "postgres" else (lambda s: s)
    ensure_schema(cursor, dialect=dialect)
    fixture = json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))
    now = datetime.now().isoformat()
    current: Dict[str, int] = {}
    for entry in fixture:
        name = entry["name"]
        cursor.execute(
            q("""INSERT INTO model_lookup (name, display_name, kind) VALUES (?, ?, ?)
               ON CONFLICT(name) DO UPDATE SET
                   display_name = excluded.display_name,
                   kind = excluded.kind"""),
            (name, entry.get("display_name"), entry.get("kind")),
        )
        cursor.execute(q("SELECT id FROM model_lookup WHERE name = ?"), (name,))
        model_id = cursor.fetchone()[0]

        fingerprint, label = _fingerprint(entry)
        cursor.execute(
            q("""INSERT INTO model_version
               (model_id, version_label, fingerprint, created_at)
               VALUES (?, ?, ?, ?)
               ON CONFLICT(model_id, fingerprint) DO NOTHING"""),
            (model_id, label, fingerprint, now),
        )
        cursor.execute(
            q("SELECT id FROM model_version WHERE model_id = ? AND fingerprint = ?"),
            (model_id, fingerprint),
        )
        current[name] = cursor.fetchone()[0]
    return current


def resolve(model_used: Optional[str]) -> str:
    """Map the free-form `model_used` string to a canonical model_lookup name.
    Mirrors app._classify_source's prefix matching."""
    if not model_used:
        return "unknown"
    m = model_used
    if m.startswith("Naive Bayes"):
        return "naive_bayes"
    if m.startswith("Neural Network"):
        return "neural_network"
    if m == "ais_mcp":
        return "ais_mcp"
    if m == "connectors_mcp":
        return "connectors_mcp"
    if m.startswith("Charter RAG"):
        return "charter_rag"
    if m.startswith("Site RAG"):
        return "site_rag"
    if m.startswith("Intent Retrieval"):
        return "intent_retrieval"
    if m.startswith("Conversation Recap"):
        return "conversation_recap"
    if m.startswith("Small Talk"):
        return "smalltalk"
    if m.startswith("College Programs"):
        return "college_programs"
    if m.startswith("NonsenseGate"):
        return "nonsense_gate"
    if m.startswith("ScopeGate") or "(out-of-scope)" in m:
        return "scope_gate"
    if m.startswith("SafetyGate"):
        return "safety_gate"
    if m.startswith("CampusContext"):
        return "campus_context"
    if m.startswith("Claude"):
        return "llm_claude"
    if m.startswith("Local LLM") or m.startswith("Ollama"):
        return "llm_local"
    return "unknown"
